[project]
name = "data-source"
version = "0.1.0"
description = "fake data source provvider"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "faker>=37.12.0",
    "fastapi>=0.121.1",
    "pydantic-settings>=2.12.0",
    "uvicorn>=0.38.0",
]
